version: '3.8'

services:
  api:
    build: .
    container_name: lyftr-api
    ports:
      - "8000:8000"
    environment:
      - WEBHOOK_SECRET=testsecret
      - DATABASE_URL=sqlite:////data/app.db
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/data
    restart: always
